# Generated by Django 3.2.7 on 2021-11-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=40)),
                ('date_published', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
